In [1]:
import numpy as np

In [5]:
#membuat array 1D
arr = np.array([1,2,3,4,5])
print(arr)

#membuat array 2D dengan arr_2d
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [7]:
#mengkalikan /menjumlah isi array dengan data
arr = np.array([1,2,3])
print(arr+5) #menambahkan semua elemen dengan 5
print(arr*2) #mengkalikan semua elemen dengan 2

[6 7 8]
[2 4 6]


In [9]:
#mencari jumlah elemen dalam array 
arr = np.array([1,2,3,4,5])
print(np.sum(arr)) #menjumlahkan elemen
print(np.mean(arr)) #rata-rata elemen
print(np.max(arr)) #nilai maksimum
print(np.min(arr)) #nilai minimum

15
3.0
5
1


In [11]:
#cara lain membuat array
arr = np.arange(0,10,2) #membuat arraydari 0 hingga 9 dengan step 2
print(arr)

[0 2 4 6 8]


In [17]:
#operasi pada array 2D
arr_2d = np.array([[1,2,3], [4,5,6]])
print(np.sum(arr_2d, axis=0)) #menjumlahkan setiap kolom
print(np.sum(arr_2d, axis=1)) #menjumlahkan setiap baris


[5 7 9]
[ 6 15]


In [21]:
#mengubah array 1D menjadi 2D
arr = np.arange(1,13)
print(arr)
arr_reshaped = arr.reshape(3,4)
print(arr_reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
#menyeleksi isi array
arr = np.array([10,20,30,40,50])
mask = arr >30
print(arr[mask]) #menampilkan elemen yang lebih besar dari 30

[40 50]


In [25]:
#menggabungkan array dan membagi array
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1, arr2)) #menggabungkan array
print(combined)

split = np.split(combined, 2) #membagi array menjadi 2 bagian
print(split)

[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]


In [27]:
#fungsi random int
rand_arr = np.random.rand(3,3) #membuat array 3x3 dengan nilai random antara 0 dan 1
print(rand_arr)

randint_arr = np.random.randint(1,10, size=(2,3)) #membuat array 2x3 dengan angka integer random
print(randint_arr)

[[0.46536223 0.29152092 0.67927783]
 [0.92718581 0.03828718 0.69757708]
 [0.47047373 0.20268699 0.23070067]]
[[4 5 7]
 [7 3 9]]


In [31]:
#fungsi scalar untuk mengkalikan/menjumlahkan angka tertentu
arr = np.array([[1,2,3], [4,5,6]])
scalar = 10
print(arr + scalar) #broadcasting menambah semua elemen dengan scalar

[[11 12 13]
 [14 15 16]]


In [33]:
#perkalian matriks
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
result = np.dot(A,B) #perkalian matriks
print(result)

#invers matriks
A_inv = np.linalg.inv(A)
print(A_inv)

[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [35]:
matrix = np.array([[1,2], [3,4]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print('Eigenvalues:', eigenvalues)
print('Eigenvectors:', eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [37]:
arr = np.array([4,2,7,1])
sorted_arr = np.sort(arr) #mengurutkan array
print(sorted_arr)

indices = np.argsort(arr) #mendapatkan index array yang diurutkan
print(indices)

[1 2 4 7]
[3 1 0 2]


In [39]:
#fungsi where untuk mengganti elemen tertentu dengan syarat
arr = np.array([10,20,30,40])
result = np.where(arr > 20, arr, -1) #ganti elemen yang lebih kecil dari 20 dengan -1
print(result)

[-1 -1 30 40]


In [41]:
#memperbaiki missing data
arr = np.array([1,2, np.nan,4,5])
print(np.isnan(arr)) #memeriksa elemen nan

#mengisi nilai nan dengan rata-rata elemen lainnya
arr[np.isnan(arr)] = np.nanmean(arr)
print(arr)

[False False  True False False]
[1. 2. 3. 4. 5.]


In [43]:
#menerapkan fungsi sinus
arr = np.array([1,2,3,4,5])
result = np.sin(arr) #fungsi sinus pada setiap elemen
print(result)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [45]:
import time

#menggunakan loop biasa
start = time.time()
result = [i**2 for i in range(10000)]
end = time.time()
print('Waktu dengan loop biasa:', end - start)

#menggunakan numpy
start = time.time()
arr = np.arange(10000)
result = arr**2
end = time.time()
print('Waktu dengan Numpy:', end - start)

Waktu dengan loop biasa: 0.006995201110839844
Waktu dengan Numpy: 0.0019981861114501953


In [49]:
array_sederhana = np.arange(1, 11)
print ( array_sederhana)

[ 1  2  3  4  5  6  7  8  9 10]


In [53]:
# Membuat array dari 1 hingga 5
array_aritmatika = np.arange(1, 6)

# Kalikan setiap elemen array dengan 3
hasil_kali = array_aritmatika * 3
print(hasil_kali)

[ 3  6  9 12 15]


In [55]:
# Membuat matriks identitas 3x3
matriks_identitas = np.eye(3)
print("Matriks identitas 3x3:\n", matriks_identitas)


Matriks identitas 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
# Membuat array acak 5x5
array_acak = np.random.rand(5, 5)

# Mencari nilai maksimum
nilai_maksimum = np.max(array_acak)
print("Array acak 5x5:\n", array_acak)
print("Nilai maksimum dalam array:", nilai_maksimum)


Array acak 5x5:
 [[0.80315293 0.56228697 0.44323448 0.72971814 0.08384799]
 [0.85219044 0.45906899 0.28578334 0.59522902 0.16599575]
 [0.23631619 0.39095065 0.71544099 0.50302622 0.30345718]
 [0.72996523 0.5997893  0.40755807 0.12476054 0.29872801]
 [0.98027454 0.82905473 0.20747842 0.21905966 0.43035814]]
Nilai maksimum dalam array: 0.9802745397893996


In [89]:
# Membuat array 1D dengan 9 elemen
array_1D = np.arange(11, 20)

# Mengubah menjadi array 2D berukuran 3x3
array_2D = array_1D.reshape(3, 3)
print("Array 2D 3x3:\n", array_2D)


Array 2D 3x3:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [75]:
# Membuat dua matriks 3x3
matrix_A = np.array([[1, 1, 3], [2, 4, 6], [1, 3, 9]])
matrix_B = np.array([[2, 8, 7], [6, 1, 4], [3, 2, 1]])

# Menghitung dot product kedua matriks
dot_product = np.dot(matrix_A, matrix_B)
print( "Dot Product kedua matriks:\n", dot_product)


Dot Product kedua matriks:
 [[17 15 14]
 [46 32 36]
 [47 29 28]]


In [77]:
# Membuat array 1D dari 1 hingga 10
array = np.arange(1, 11)

# Mengambil elemen pada indeks 3 sampai 7 (dari elemen ke-4 hingga ke-8)
sliced_array = array[3:8]
print("Elemen indeks 3 sampai 7:", sliced_array)


Elemen indeks 3 sampai 7: [4 5 6 7 8]


In [79]:
# Membuat dua array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Menggabungkan kedua array
array_gabungan = np.concatenate((a, b))
print("Array gabungan:", array_gabungan)

Array gabungan: [1 2 3 4 5 6]


In [81]:
# Membuat array dari 1 hingga 4
array_broadcast = np.array([1, 2, 3, 4])

# Menambahkan 10 ke setiap elemen array menggunakan broadcasting
array_broadcast += 10
print("Array setelah ditambah 10:", array_broadcast)


Array setelah ditambah 10: [11 12 13 14]


In [87]:
# Membuat array acak berisi 10 elemen
array_acak = np.random.randint(1, 91, size=10)

# Mengurutkan array
array_urut = np.sort(array_acak)
print("Array acak:", array_acak)
print("Array setelah diurutkan:", array_urut)


Array acak: [24 46 77 25 48 51 88  5 57 50]
Array setelah diurutkan: [ 5 24 25 46 48 50 51 57 77 88]
